spring:
  application:
    name: employee
  datasource:
    url: jdbc:postgresql://localhost:5431/employee
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.master-changelog.xml